export const SKILL_PHRASES: readonly string[] = [
  'machine learning',
  'deep learning',
  'artificial intelligence',
  'natural language processing',
  'computer vision',
  'data science',
  'data engineering',
  'data analysis',
  'data analytics',
  'data warehouse',
  'data modeling',
  'data visualization',
  'business intelligence',
  'big data',
  'cloud computing',
  'ci cd',
  'continuous integration',
  'continuous delivery',
  'api development',
  'rest api',
  'restful api',
  'microservices',
  'software engineering',
  'software development',
  'full stack',
  'fullstack',
  'front end',
  'frontend',
  'back end',
  'backend',
  'product management',
  'project management',
  'program management',
  'stakeholder management',
  'cyber security',
  'information security',
  'network security',
  'incident response',
  'threat intelligence',
  'penetration testing',
  'release engineering',
  'site reliability',
  'time series',
  'supply chain',
  'business analysis',
  'financial analysis',
  'risk management',
  'digital marketing',
];
