/**
 * The platform's declared interest: the exact job titles we track.
 * A listing is in scope only when its title matches one of these roles.
 */
export const TARGET_ROLES: readonly string[] = [
  'Full-Stack Developer',
  'Senior Full-Stack Developer',
  'Lead Full-Stack Developer',
  'Lead Frontend Developer',
  'Frontend Developer',
  'Frontend Engineer',
  'Frontend Architect',
  'Senior Frontend Developer',
  'Full-Stack Tech Lead',
  'Frontend Tech Lead',
  'Technical Lead',
  'Software Engineer',
  'Senior Software Engineer',
  'Digital Platform Engineer',
  'Web Platform Engineer',
  'E-commerce Technical Lead',
  'E-commerce Solutions Architect',
  'CMS Solutions Architect',
  'Headless CMS Developer',
  'Headless CMS Architect',
  'Technical Consultant',
  'Senior Technical Consultant',
  'Digital Solutions Consultant',
  'Technology Consultant',
  'Technical Implementation Consultant',
  'Professional Services Consultant',
  'Senior Implementation Consultant',
  'Digital Transformation Consultant',
  'Cloud Application Consultant',
  'Azure Application Developer',
  'Azure DevOps Engineer',
  'DevOps Engineer',
  'Application Platform Engineer',
  'Integration Developer',
  'Integration Consultant',
  'API Integration Specialist',
  'Technical Business Analyst',
  'Business Systems Analyst',
  'Solutions Engineer',
  'Sales Engineer',
  'Customer Solutions Engineer',
  'Technical Account Manager',
  'Customer Success Engineer',
  'Customer Enablement Specialist',
  'Solutions Delivery Manager',
  'Technical Delivery Manager',
  'AI Solutions Architect',
  'AI Application Engineer',
  'Generative AI Engineer',
  'AI Integration Engineer',
  'AI Automation Engineer',
  'Intelligent Automation Consultant',
  'AI Adoption Consultant',
  'AI Enablement Specialist',
  'AI Transformation Consultant',
  'AI Product Consultant',
  'AI Implementation Consultant',
  'AI Solutions Consultant',
  'AI Technical Consultant',
  'AI Customer Success Engineer',
  'AI Solutions Engineer',
  'AI Platform Engineer',
  'Applied AI Engineer',
  'Data Engineer',
  'Senior Data Engineer',
  'Lead Data Engineer',
  'Analytics Engineer',
  'ML Engineer',
  'Machine Learning Engineer',
  'Senior Machine Learning Engineer',
  'MLOps Engineer',
  'Data Platform Engineer',
  'AI Product Specialist',
  'Automation Architect',
  'Workflow Automation Architect',
  'Business Automation Consultant',
  'Digital Automation Consultant',
  'Automation Solutions Architect',
  'AI Governance and Adoption Consultant',
  'Responsible AI Consultant',
  'AI Product Manager',
  'Technical Product Manager, AI',
  'AI Technical Program Manager',
  'Technical Product Manager',
  'Senior Technical Product Manager',
  'Digital Product Manager',
  'Product Manager, Digital Platforms',
  'Product Manager, Web Platforms',
  'Product Manager, Developer Experience',
  'Product Manager, Content Platform',
  'Product Manager, E-commerce',
  'Product Manager, AI and Automation',
  'Product Owner',
  'Technical Product Owner',
  'Digital Product Owner',
  'Platform Product Owner',
  'Product Operations Manager',
  'Product Delivery Manager',
  'Product Enablement Manager',
  'Product Solutions Manager',
  'Technical Program Manager',
  'Digital Program Manager',
  'Digital Transformation Manager',
  'Digital Transformation Lead',
  'Technology Transformation Manager',
  'Digital Strategy Consultant',
  'Technology Strategy Consultant',
  'Digital Experience Consultant',
  'Customer Experience Technology Consultant',
  'Business Technology Consultant',
  'IT Management Consultant',
  'Enterprise Applications Consultant',
  'Digital Platforms Consultant',
  'Web Strategy Consultant',
  'CMS Strategy Consultant',
  'E-commerce Consultant',
  'E-commerce Manager',
  'Digital Operations Manager',
  'Business Process Improvement Consultant',
  'Process Automation Consultant',
  'Business Systems Consultant',
  'Technology Enablement Manager',
  'Digital Enablement Manager',
  'Innovation Consultant',
  'Innovation Manager',
  'Technology Innovation Manager',
  'Digital Innovation Lead',
  'AI Innovation Consultant',
  'AI Transformation Manager',
  'Digital Change Consultant',
  'Change and Adoption Consultant',
  'Customer Technology Advisor',
  'Technical Advisor',
  'Technical Project Manager',
  'Digital Project Manager',
  'Software Delivery Manager',
  'Engineering Delivery Manager',
  'Digital Delivery Manager',
  'Technology Delivery Lead',
  'Client Delivery Manager',
  'Implementation Project Manager',
  'Platform Delivery Manager',
  'Web Delivery Manager',
  'Agile Delivery Manager',
  'Scrum Master',
  'Engagement Manager',
  'Client Engagement Manager',
  'Technical Engagement Manager',
  'Programme Manager, Digital Transformation',
  'Program Manager, AI Enablement',
  'Transformation Programme Manager',
  'Solution Architect',
  'Digital Solutions Architect',
  'Application Architect',
  'Cloud Solutions Architect',
  'Enterprise Solutions Architect',
  'Technical Architect',
  'Integration Architect',
  'Commerce Architect',
  'Content Platform Architect',
  'Platform Architect',
  'Digital Experience Architect',
  'Principal Engineer',
  'Staff Engineer',
  'Engineering Manager',
  'Frontend Engineering Manager',
  'Software Development Manager',
  'Head of Engineering',
  'Head of Digital Platforms',
  'Head of Web',
  'Web Engineering Manager',
  'Head of Digital Experience',
  'Head of Technology, Digital',
  'Director of Engineering',
  'Director of Digital Transformation',

  // Swedish-market equivalents of the roles above. Several source boards
  // (Nion, Xamera, Keyman) post almost exclusively in Swedish, and the
  // regex/vector matching this list feeds is otherwise English-only - a
  // clearly in-scope title like "Mjukvaruutvecklare" in Gothenburg would
  // never match without one of these. `seedTargetRolePhrases` embeds every
  // entry in this file, so these also seed the vector-similarity fallback.
  'Systemutvecklare',
  'Mjukvaruutvecklare',
  'Frontendutvecklare',
  'Backendutvecklare',
  'Fullstackutvecklare',
  'Applikationsutvecklare',
  'Molnutvecklare',
  'Integrationsutvecklare',
  'Embeddedutvecklare',
  'AI-utvecklare',
  'Android-utvecklare',
  'iOS-utvecklare',
  'DevOps-ingenjör',
  'Systemingenjör',
  'Systemarkitekt',
  'Molnarkitekt',
  'Lösningsarkitekt',
  'Mjukvaruarkitekt',
  'Dataingenjör',
  'BI-utvecklare',
  'Teknisk konsult',
  'IT-konsult',
  'Systemkonsult',
  'Molnkonsult',
  'DevOps-konsult',
  'Säkerhetsingenjör',
  'Säkerhetsarkitekt',
  'IT-säkerhetskonsult',
  'Cybersäkerhetsspecialist',
  'IT-projektledare',
  'Teknisk projektledare',
  'Produktägare',

  // Bare generic-suffix nouns, deliberately not paired with a prefix.
  // Swedish compounds developer/consultant titles into one fused word
  // ("PHP-utvecklare", "SAP SuccessFactors-konsult") rather than the
  // space-separated "Core Phrase + Suffix" shape GENERIC_TITLE_SUFFIXES
  // (target-filter.ts) already makes optional for English - there's no
  // finite prefix list to curate, so these match on the suffix alone.
  // Limited to "utvecklare"/"konsult": every "-utvecklare" observed on the
  // Nion/Xamera/Keyman boards is a software role, and "-konsult" postings
  // on these IT-focused boards read the same way; "-ingenjör"/"-arkitekt"
  // are deliberately NOT made generic here - both pull in unrelated
  // mechanical/electrical engineering titles from the same boards
  // (e.g. "Mekanikingenjör", "Elektronikingenjör") that plain word-suffix
  // matching can't tell apart from the software/IT kind.
  'Utvecklare',
  'Konsult',
];
