import { Ollama } from 'ollama';
import { createOllamaFetch, type OllamaConfig } from './ollama';

export type LayaVerdict = 'strong' | 'moderate' | 'weak';

export interface LayaEvaluation {
  /** 0-1, normalized from Laya's ordinal `fit` rubric score. */
  score: number;
  choice: LayaVerdict;
  /** Positive-only explanation of why the candidate fits, generated by Ollama - see note below. */
  reasoning: string;
  /** Negative-only explanation of the candidate's gaps against the job - never mixed into `reasoning`. */
  mismatchReasoning: string;
}

export interface LayaClient {
  evaluate(input: { jobText: string; cvText: string }): Promise<LayaEvaluation>;
}

export interface LayaConfig {
  /** Base URL of a self-hosted `laya-serve` instance, e.g. http://localhost:8001. */
  apiUrl: string;
  /** Sent as `Authorization: Bearer <apiKey>` when set (matches `LAYA_API_KEY` on the server). */
  apiKey?: string;
}

/**
 * Laya (https://github.com/NandhaKishorM/laya) is a non-autoregressive BERT
 * classifier, not a generative model - its `/v1/systemone` endpoint returns
 * typed labels/scores/confidences but never free text (see its README's
 * "no text generation, so nothing to hallucinate" design point). It gives
 * the calibrated score/verdict half of a Laya evaluation; the `reasoning`
 * string is a *separate* concern, generated by the existing local Ollama
 * model via `ReasoningGenerator` below and stitched together here into one
 * `LayaEvaluation` - decided this way (rather than dropping reasoning, or
 * treating Laya's raw probabilities as pseudo-reasoning) since a hard match
 * percentage plus a written "why" is what the UI (Decision 6) needs.
 */
export interface ReasoningResult {
  reasoning: string;
  mismatchReasoning: string;
}

export interface ReasoningGenerator {
  generate(input: {
    jobText: string;
    cvText: string;
    verdict: LayaVerdict;
    score: number;
  }): Promise<ReasoningResult>;
}

/** Ordinal rubric sent to Laya's `score` question type - 3 rungs, weak=0..strong=2. */
const FIT_RUBRIC = ['weak', 'moderate', 'strong'] as const;

const LAYA_QUESTIONS = {
  verdict: {
    type: 'choice',
    instructions:
      'How well does this candidate CV match the job description\'s core requirements?',
    criteria: {
      strong: "Candidate clearly meets or exceeds the job's core requirements.",
      moderate:
        'Candidate partially matches: meets some requirements but has notable gaps.',
      weak: "Candidate does not match the job's core requirements.",
    },
  },
  fit: {
    type: 'score',
    instructions:
      'Rate how well this candidate CV fits the job description overall, from weak to strong.',
    criteria: [...FIT_RUBRIC],
  },
} as const;

interface LayaSystemOneResponse {
  answers: {
    verdict?: { choice: LayaVerdict; confidence: number };
    fit?: { score: number; confidence: number };
  };
}

function isLayaVerdict(value: unknown): value is LayaVerdict {
  return value === 'strong' || value === 'moderate' || value === 'weak';
}

async function callSystemOne(
  config: LayaConfig,
  jobText: string,
  cvText: string,
): Promise<{ verdict: LayaVerdict; rawScore: number }> {
  const response = await fetch(`${config.apiUrl.replace(/\/$/, '')}/v1/systemone`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      ...(config.apiKey ? { authorization: `Bearer ${config.apiKey}` } : {}),
    },
    body: JSON.stringify({
      state: { job: jobText, cv: cvText },
      questions: LAYA_QUESTIONS,
    }),
  });
  if (!response.ok) {
    throw new Error(`Laya request failed: HTTP ${response.status}`);
  }
  const body = (await response.json()) as LayaSystemOneResponse;
  const verdict = body.answers.verdict?.choice;
  const rawScore = body.answers.fit?.score;
  if (!isLayaVerdict(verdict) || typeof rawScore !== 'number') {
    throw new Error('Laya response missing expected "verdict"/"fit" answers');
  }
  return { verdict, rawScore };
}

export function createLayaClient(
  config: LayaConfig,
  reasoner: ReasoningGenerator,
): LayaClient {
  return {
    async evaluate({ jobText, cvText }) {
      const { verdict, rawScore } = await callSystemOne(config, jobText, cvText);
      const score = Math.max(
        0,
        Math.min(1, rawScore / (FIT_RUBRIC.length - 1)),
      );
      const { reasoning, mismatchReasoning } = await reasoner.generate({
        jobText,
        cvText,
        verdict,
        score,
      });
      return { score, choice: verdict, reasoning, mismatchReasoning };
    },
  };
}

const MATCH_MARKER = 'MATCH:';
const MISMATCH_MARKER = 'MISMATCH:';

const REASONING_SYSTEM_PROMPT =
  'You are a recruiter assistant writing text that will be pasted directly ' +
  'into a message to a hiring manager or candidate, so it must read as ' +
  'natural, flowing prose - never a bulleted or fragmented list, never ' +
  'terse. Given a job description and a candidate CV, plus a verdict/score ' +
  'another system already computed, write TWO SEPARATE explanations and ' +
  'never mix a positive point into the negative one or vice versa. If a ' +
  'single thought contains both a strength and a gap ("has X but lacks ' +
  'Y"), split it into two sentences and place each half in its correct ' +
  'section below.\n\n' +
  `1. Under the exact line "${MATCH_MARKER}", write a full paragraph of ` +
  "5-8 sentences, entirely positive, on why the candidate fits: which of " +
  "the job's specific requirements the candidate's experience, skills, or " +
  'projects satisfy, citing concrete details from both documents (not ' +
  'generic praise like "strong communicator"). Crucially, for every ' +
  "requirement the candidate doesn't meet verbatim, actively look for " +
  'closely related, transferable experience before treating it as a gap - ' +
  'e.g. React experience reasonably supports Vue or Angular; one cloud ' +
  'provider (AWS/Azure/GCP) supports another; one SQL database supports ' +
  'another; a similar domain, framework, methodology, or tool counts as ' +
  'relevant. Spell out that transferable connection explicitly as its own ' +
  'sentence ("Although the CV does not mention <X>, the candidate has ' +
  '<related Y>, which transfers directly because <reason>") and count it ' +
  'as a point in favor, never as a gap.\n\n' +
  `2. Under the exact line "${MISMATCH_MARKER}", write a full paragraph ` +
  "of 3-5 sentences, entirely negative, covering ONLY the candidate's " +
  "genuine gaps against the job's requirements - requirements with no " +
  'reasonably transferable experience behind them (those belong in ' +
  `${MATCH_MARKER} instead). Do not just list missing skill names - for ` +
  'each real gap, explain in a full sentence what the requirement is and ' +
  'why nothing in the CV reasonably covers it. Do not restate or soften ' +
  'this with any positive point; if there are no real gaps, say so ' +
  'plainly in one sentence.\n\n' +
  'Do not repeat the raw verdict/score back verbatim, and do not invent ' +
  'facts not present in either document. Reply with exactly those two ' +
  'labeled sections as prose paragraphs, no preamble, no markdown, no ' +
  'bullet points.';

function findMarker(
  content: string,
  marker: string,
): { start: number; end: number } | null {
  // Tolerate the model varying case or wrapping the marker in markdown
  // emphasis (**MATCH:**) despite being told not to - a literal indexOf
  // would otherwise miss it and silently collapse both sections together.
  const match = new RegExp(`\\**${marker.replace(':', '')}:\\**`, 'i').exec(
    content,
  );
  return match ? { start: match.index, end: match.index + match[0].length } : null;
}

export function parseReasoningResponse(content: string): ReasoningResult {
  const matchMarker = findMarker(content, MATCH_MARKER);
  const mismatchMarker = findMarker(content, MISMATCH_MARKER);

  if (!matchMarker || !mismatchMarker || mismatchMarker.start < matchMarker.start) {
    // Model didn't follow the format - fall back to treating the whole
    // response as the positive reasoning rather than losing it.
    return { reasoning: content.trim(), mismatchReasoning: '' };
  }

  const reasoning = content.slice(matchMarker.end, mismatchMarker.start).trim();
  const mismatchReasoning = content.slice(mismatchMarker.end).trim();
  return { reasoning, mismatchReasoning };
}

/** Generates the `reasoning`/`mismatchReasoning` text via the same local Ollama model used for sanitization. */
export function createOllamaReasoner(config: OllamaConfig): ReasoningGenerator {
  const client = new Ollama({ host: config.host, fetch: createOllamaFetch() });

  return {
    async generate({ jobText, cvText, verdict, score }) {
      const response = await client.chat({
        model: config.chatModel,
        messages: [
          { role: 'system', content: REASONING_SYSTEM_PROMPT },
          {
            role: 'user',
            content:
              `Job description:\n${jobText}\n\nCandidate CV:\n${cvText}\n\n` +
              `Computed verdict: ${verdict} (score ${score.toFixed(2)})`,
          },
        ],
        options: {
          temperature: 0,
          num_ctx: config.numCtx,
          num_predict: config.numPredict,
        },
      });
      return parseReasoningResponse(response.message.content);
    },
  };
}
